### ISSUE TITLE
Player does not clear screen/does not respect cursor position.

### ISSUE THREAD

**Issue by peterdell** [ivop/saprtools#3]
I am assembling the SillyPack for SV2k23 WE and want every converted tune playable directly from the menu.
The player code assumes the screen is cleared and prints the time at line 12.
This creates wrong output if another text is already printed, such as the file name.

![image](https://github.com/user-attachments/assets/be9d01dd-c426-48cb-a7f2-a6a791ebe662)

It would be great if the player used the last line (ROWCRS)+2 to print the time.
This way, the filename is still visible (relevant if you have 18 files here), and the time printing would be correct.
Alternatively the player should clear the screen by printing CHR$(125) first.

**Comment by peterdell** [comment]
Note: I've managed to fork and build this on my MacBook and will try to provide a pull request

**Comment by ivop** [comment]
I added clear screen to all the players. Hope this helps :)

Re macOS, I'll happily merge patches to build everything on macOS. I only have a Catalina virtual machine, as later versions only run single core in VirtualBox or won't run at all.
